### ISSUE TITLE
Clarifications in the readme

### ISSUE THREAD

**Issue by addyosmani** [hull-graveyard/hullagram#16]
Pretending that I was looking at the project for the first time, I think it would be useful to explain in the readme what parts of the source (maybe just directories) are pulled in/installed using Hull and what parts compose the application wiring everything together.

My worry is that by not doing that a developer might think you wrote all the widgets by hand just for this project.

Does that make sense?

**Comment by unity** [comment]
Indeed it does !
Working on it.

**Comment by addyosmani** [comment]
Awesome. Thanks!

**Comment by sbellity** [comment]
@addyosmani I just added a section "Anatomy of Hullagram" in the README, wdyt ?

**Comment by addyosmani** [comment]
That's ideal!. Two small pieces of feedback:
- I would move the additions you've made to higher up in the readme before installing
- Link up "Hull platform" to hull.io/a doc/page that explains what the Hull platform is as it's the first mention of it in the readme.

Otherwise, great work!

**Comment by sbellity** [comment]
thx
