### ISSUE TITLE
Changing a custom component's template with routes

### ISSUE THREAD

**Issue by HiggsOfChaos** [hull-graveyard/hullagram#21]
I have a custom widget i created in my Hullogram wannabe app but I cant seem to get the view to render different templates based on the route. I have been able to create a basic route object and the route event fires but I do not know how to access the render("template) method of its containing component (widget)

Here is my component code

Hull.widget("appviews",{
  datasources: {

```
  }, //List data sources you want to use here
```

  templates: ["main","rate"], //Declare the template names you use here

  initialize: function () {
      this.initRouter();

```
  }, //Called at component initialization

draw: function() {

},
```

  beforeRender: function (data, errors) {

```
  }, //Called after datasources are resolved
```

  afterRender: function () {

```
  }, //Called after template has been rendered - put jQuery plugin calls here
```

  /\* append your own components methods */

  initRouter: function(){

```
  console.log("init router fired");

var Backbone = Hull.require('backbone'),
    _        = Hull.require('underscore');


var FotoRouter = Backbone.Router.extend({
  initialize: function() {
    this.routesHit = 0;
    //keep count of number of routes handled by your application
    Backbone.history.on('route', function() { this.routesHit++; }, this);
  },
  routes: {
      "rate":"rate"
  },

  rate: function() {
      console.log("rate hash fired");


  }

});

var router  = new FotoRouter();



Backbone.history.start();
```

  } /// End initRouter

});

**Comment by sbellity** [comment]
Do you have the code source available on github ?

**Comment by HiggsOfChaos** [comment]
No. Its not on github. Its just a simple test app really. I'm trying to learn how to use Hull.io and Backbone. The only thing I don't seem to get is to make the above widget render a different template depending on the route.

**Comment by sbellity** [comment]
You should be able to just call the render method in your route handler.

This is how it's done in hullagram :: 

https://github.com/hull/hullagram/blob/develop/app/widgets/app/main.js#L85
