### ISSUE TITLE
Replace hullagram with own server

### ISSUE THREAD

**Issue by asennoussi** [hull-graveyard/hullagram#25]
Hello ! 
Can I replace hullagram with my own backend ?

**Comment by unity** [comment]
The app is meant as a demo of Hull.io's backend. You could rebuild a backend but I suspect it would take quite a bit of time and expertise. If you can achieve this then this demo should be quite easy to rebuild :)

Moreover the code for this demo is getting quite old and there are now better tools than those existing at the time.

Did you try creating a (free) account at hull.io ?
