### ISSUE TITLE
Likes image spacing issue

### ISSUE THREAD

**Issue by addyosmani** [hull-graveyard/hullagram#4]
On desktop, if you view your likes there is currently a weird amount of spacing between images. Let me know if you require a screenshot, but with more than 1 liked image it should show up.

**Comment by Victa** [comment]
hmm... looks normal to me?

![Hullagram](https://f.cloud.github.com/assets/594365/149089/48512acc-7520-11e2-9817-1eea9bb6b329.png)

**Comment by addyosmani** [comment]
I think with the updated layout (narrower layout) this issue should be resolved now.

**Comment by Victa** [comment]
cool!
